import Head from "next/head";
import Image from "next/image";
import { useAuth } from "@/context/AuthContext";
import Login from "@/components/Login";
import QuotesFeed from "@/components/QuotesFeed";
import { collection } from "firebase/firestore";

export default function Home() {
  const { currentUser } = useAuth();
  console.log(`currentUser`, currentUser);

  return (
    <>
      <Head>
        <title>Quoted</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <QuotesFeed />}
    </>
  );
}
