import Head from "next/head";
import Image from "next/image";
import { useAuth } from "@/context/AuthContext";
import Login from "@/components/Login";
import QuotesFeed from "@/components/QuotesFeed";

export default function Home() {
  const { currentUser } = useAuth();
  console.log(currentUser);

  return (
    <>
      <Head>
        <title>Quoted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <QuotesFeed />}
    </>
  );
}
